server:
  port: 8086



spring:
  application:
    name: bankbalance
  h2:
    console:
      enabled: true
      path: /h2-console
    datasource:
      url: jdbc:h2:mem:bankdb
  datasource:
    url: jdbc:h2:mem:bankdb
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update

spring.cloud.aws:
  region:
    static: sa-east-1
  credentials:
    access-key: test
    secret-key: test
  sqs:
    endpoint: http://localhost:4566


spring.cloud.aws.sqs.listener.max-concurrent-messages: 50